### ISSUE TITLE
null or undefined object throws error

### ISSUE THREAD

**Issue by szkrd** [75lb/object-get#1]
here: https://github.com/75lb/object-get/blob/9584df49f0fead4409123a07550d364b570dcac6/lib/object-get.js#L45

probably arguments.length !== 2 would be better.

**Comment by 75lb** [comment]
hi! but `arguments.length !== 2` doesn't test the truthiness of the inputs (i.e. passing in junk like `objectGet(undefined, null)` would pass your test..)

what's your high-level issue out of interest? I assume you traced a bug to this module from somewhere higher up the tree..

**Comment by 75lb** [comment]
the current behaviour of `objectGet(object, expression)` is that it will throw if either `object` or `expression` are undefined or null - this is the desired behaviour, anything else would be a breaking change. 

What do i need to fix, here?

**Comment by szkrd** [comment]
I usually expect "get" to be error resistant, kinda like _.get in lodash. To me it doesn't really matter if the input is null, I want object-get to be silent (probably that's why I'm using it in the first place). I can understand that the thrown error is a design decision and not a bug, so I close this issue. Thank you!
