### ISSUE TITLE
nested arrays

### ISSUE THREAD

**Issue by sz-k** [75lb/object-get#2]
```javascript
x = {a: [{b:1}, {c:1}, {d:1}, [0,1,2,3,4] ]};
console.log(objectGet(x, 'a[3][4]')); // expected 4, got [0,1,2,3,4]
```

It's not really a big deal, but since there is a condition in the code for handling arrays, it may be nice to be careful.

This may be kinda sloppy as a solution, don't know:
`expression.trim().split(/[\[\.]/).reduce((prev, curr) => prev && prev[curr.replace(/]$/, '')], object)`

**Comment by 75lb** [comment]
hi there.. does [`_.get`](https://lodash.com/docs/4.17.4#get) return the expected result?

**Comment by akileez** [comment]
I usually access nested arrays via this syntax…

```js
console.log(objectGet(x, ‘a.3.4’)) // yields 4
```
not sure if this helps but an idea.

**Comment by szkrd** [comment]
Hi @75lb thanks for the quick answer! Yes, lodash `_.get` works, but we're not using it as a dependency unfortunately.

@akileez the dot notation works of course, but that works a tiny bit differently

I know this may look like nitpicking, but vuejs uses getters and setters on objects and "not calling" an interim getter (in this case the array) will give different results.

**Comment by 75lb** [comment]
ok.. i think the quickest solution for you would be to use lodash `_.get`.. i will leave this ticket open but it's not a top priority right now, sorry.

**Comment by szkrd** [comment]
No problem, we're going to come up w smg :)
